### ISSUE TITLE
existsDelegate does not exist on type 'Prisma'

### ISSUE THREAD

**Issue by parweb** [Urigo/graphql-cli#316]
Hi

I cloned the project, a while ago it was working fine until 2 or 3 weeks
https://github.com/prismagraphql/graphql-server-example

versions:
- node: v10.3.0
- npm: 6.1.0

package.json
```
{
  "name": "backend",
  "version": "1.0.0",
  "scripts": {
    "dev": "npm-run-all --parallel start playground",
    "start": "nodemon -e ts,graphql -x ts-node -r dotenv/config src/index.ts",
    "playground": "graphql playground",
    "build": "rm -rf dist && graphql codegen && tsc",
    "prisma": "prisma"
  },
  "dependencies": {
    "apollo-engine": "1.1.1",
    "aws-sdk": "2.250.1",
    "bcryptjs": "2.4.3",
    "content-type": "1.0.4",
    "express": "4.16.3",
    "graphql-yoga": "1.14.6",
    "jsonwebtoken": "8.2.2",
    "mime-types": "2.1.18",
    "multiparty": "4.1.4",
    "ndjson": "1.5.0",
    "prisma-binding": "2.0.2",
    "raw-body": "2.3.3",
    "request": "2.87.0",
    "uuid": "3.2.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "dotenv": "6.0.0",
    "graphql-cli": "2.16.1",
    "nodemon": "1.17.5",
    "npm-run-all": "4.1.3",
    "prisma": "1.8.3",
    "ts-node": "6.1.0",
    "typescript": "^2.9.1"
  },
  "prettier": {
    "semi": false,
    "trailingComma": "all",
    "singleQuote": true
  }
}
```

src/generated/prisma.ts(14087,62): error TS2339: Property 'existsDelegate' does not exist on type 'Prisma'.

**Comment by pixelbacon** [comment]
++

Same issue, same versions.

**Comment by codepunkt** [comment]
newer `prisma` and `prisma-binding` versions, same problem.

**Comment by pixelbacon** [comment]
I believe the issue is using `prisma-ts`, compared to now directly using `prisma-bindings` as seen in the [prisma/graphql-example-server](https://github.com/prismagraphql/graphql-server-example)

Got it working using the following `.graphqlconfig.yml`

```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:4000"
  db:
    schemaPath: src/generated/database.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
```

**Comment by fcosrno** [comment]
For me it started when I upgraded "prisma-bindings" from 1.x. Resolved after following this advice: 

https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3/#upgrading-from-prisma-binding-v1.x

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` .
Checkout new instructions and we will be happy to hear your feedback. Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

This was a complete rewrite!

Please let us know if that issue is still relevant with the new structure.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
